[package]
name = "fps_unlocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.44"
directories = "5.0.0"
egui = "0.21.0"
eframe = "0.21.3"
rfd = "0.11.3"